baseURL = "https://talks.oczadly.io/"
languageCode = "pl-pl"
title = "Paweł Oczadły: Talks"

theme = ["github.com/joshed-io/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML"]
